### ISSUE TITLE
На среднем экране у картинки слайдера нарушены пропорции

### ISSUE THREAD

**Issue by tsvetkovamaria** [saikalkaparbekova/-html_group_8_homework_34_saikal_kaparbekova#7]
В верстке у картинок разметки можно изменять размеры, но нельзя нарушать пропорции. Сейчас картинка слайдера на первом экране растынута по высоте и человек на картинке выглядит непропорционально
http://prntscr.com/ek4slx 

Подумайте, как можно изменить свойства для картинки, чтобы она растягивалась по ширине, но сохраняла пропорцию по высоте.

**Comment by saikalkaparbekova** [comment]
исправила
