### ISSUE TITLE
Мобильная версия шапки и меню выглядит неаккуратно

### ISSUE THREAD

**Issue by tsvetkovamaria** [saikalkaparbekova/-html_group_8_homework_34_saikal_kaparbekova#8]
В макете нет варианта дизайна для мобильно версии, и его нужно придумывать самостоятельно. Но какое бы решение вы не приняли, окончательный дизайн должен выглядеть аккуратно.

Сейчас мобильное меню и шапка выглядят недоделанными:
http://prntscr.com/ek4tq5
1. Вертикальное выравнивание логотипа. 
Сверху от логотипа нет отступа вовсе, а снизу он слишком большой. Лучше, если у логотипа и сверху, и снизу будет одинаковое расстояние отступа.

2. Вертикальное выравнивание элементов внутри шапки. 
Логотип и гамбургер визуально должны располагаться на одной горизонтальной линии

3. В меню есть сверху большой отступ, его нужно убрать

4. Кнопка в выпадающем меню выглядит как пункт меню
Она должна быть выровнена от левого края (либо ее текст, либо ее граница).

**Comment by saikalkaparbekova** [comment]
исправила
